import { CreatePlanDTO } from "./CreatePlanDTO";
import { UpdatePlanDTO } from "./UpdatePlanDTO";
import { CreatePlanFullDTO } from "./CreatePlanFullDTO";
import { UpdatePlanFullDTO } from "./UpdatePlanFullDTO";
import { Plan } from "@proodos/domain/Entities/Plan";

export const mapCreatePlanDTOToEntity = (dto: CreatePlanDTO): Plan => ({
  nombre: dto.nombre,
  capacidad: dto.capacidad,
  capacidad_anterior: dto.capacidad_anterior,
  precio_full_price: dto.precio_full_price,
  precio_oferta: dto.precio_oferta,
  aumento: dto.aumento,
  precio_sin_iva: dto.precio_sin_iva,
  segmento: null,
  producto: null,
  bonete: null,
  nombre_plan: null,
  capacidad_plan: null,
  tag_1: null,
  tag_2: null,
  beneficio_1: null,
  beneficio_2: null,
  beneficio_3: null,
  beneficio_4: null,
  cta_1: null,
  link_1: null,
  cta_2: null,
  link_2: null,
  precio_tv_digital: null,
  precio_tv_max: null,
  promo_activa: null,
  muestra_desde: null,
  canales_tv_digital: null,
  canales_tv_max: null,
  precio_no_cliente: null,
  descripcion_oferta: null,
  comercial_name: null,
  comercial_id: null,
  telefono_0800: null,
  icono_tag_1: null,
  pre_beneficio_2_titulo: null,
  pre_beneficio_2_descripcion: null,
  pre_beneficio_1_titulo: null,
  pre_beneficio_1_descripcion: null,
  nombre_plan_tv: null,
  grilla_canales: null,
  icono_bonete: null,
  id_plan: 0,
});

export const mapUpdatePlanDTOToEntity = (dto: UpdatePlanDTO): Plan => ({
  id_plan: dto.id_plan,
  nombre: dto.nombre,
  capacidad: dto.capacidad,
  capacidad_anterior: dto.capacidad_anterior,
  precio_full_price: dto.precio_full_price,
  precio_oferta: dto.precio_oferta,
  aumento: dto.aumento,
  precio_sin_iva: dto.precio_sin_iva,
});

const normalizeNullableString = (value: string | null | undefined) =>
  value === undefined ? null : value;

const normalizeNullableNumber = (value: number | null | undefined) =>
  value === undefined ? null : value;

const normalizeNullableBoolean = (value: boolean | null | undefined) =>
  value === undefined ? null : value;

export const mapCreatePlanFullDTOToEntity = (dto: CreatePlanFullDTO): Plan => ({
  id_plan: 0,
  segmento: normalizeNullableString(dto.segmento),
  producto: normalizeNullableString(dto.producto),
  bonete: normalizeNullableString(dto.bonete),
  nombre: normalizeNullableString(dto.nombre),
  nombre_plan: normalizeNullableString(dto.nombre_plan),
  capacidad: normalizeNullableNumber(dto.capacidad),
  capacidad_plan: normalizeNullableString(dto.capacidad_plan),
  capacidad_anterior: normalizeNullableNumber(dto.capacidad_anterior),
  precio_full_price: normalizeNullableNumber(dto.precio_full_price),
  precio_oferta: normalizeNullableNumber(dto.precio_oferta),
  tag_1: normalizeNullableString(dto.tag_1),
  tag_2: normalizeNullableString(dto.tag_2),
  beneficio_1: normalizeNullableString(dto.beneficio_1),
  beneficio_2: normalizeNullableString(dto.beneficio_2),
  beneficio_3: normalizeNullableString(dto.beneficio_3),
  beneficio_4: normalizeNullableString(dto.beneficio_4),
  cta_1: normalizeNullableString(dto.cta_1),
  link_1: normalizeNullableString(dto.link_1),
  cta_2: normalizeNullableString(dto.cta_2),
  link_2: normalizeNullableString(dto.link_2),
  aumento: normalizeNullableNumber(dto.aumento),
  precio_tv_digital: normalizeNullableNumber(dto.precio_tv_digital),
  precio_tv_max: normalizeNullableNumber(dto.precio_tv_max),
  promo_activa: normalizeNullableBoolean(dto.promo_activa),
  muestra_desde: normalizeNullableString(dto.muestra_desde),
  canales_tv_digital: normalizeNullableString(dto.canales_tv_digital),
  canales_tv_max: normalizeNullableString(dto.canales_tv_max),
  precio_no_cliente: normalizeNullableNumber(dto.precio_no_cliente),
  descripcion_oferta: normalizeNullableString(dto.descripcion_oferta),
  comercial_name: normalizeNullableString(dto.comercial_name),
  comercial_id: normalizeNullableString(dto.comercial_id),
  telefono_0800: normalizeNullableString(dto.telefono_0800),
  icono_tag_1: normalizeNullableString(dto.icono_tag_1),
  pre_beneficio_2_titulo: normalizeNullableString(dto.pre_beneficio_2_titulo),
  pre_beneficio_2_descripcion: normalizeNullableString(dto.pre_beneficio_2_descripcion),
  pre_beneficio_1_titulo: normalizeNullableString(dto.pre_beneficio_1_titulo),
  pre_beneficio_1_descripcion: normalizeNullableString(dto.pre_beneficio_1_descripcion),
  nombre_plan_tv: normalizeNullableString(dto.nombre_plan_tv),
  grilla_canales: normalizeNullableString(dto.grilla_canales),
  icono_bonete: normalizeNullableString(dto.icono_bonete),
  precio_sin_iva: normalizeNullableNumber(dto.precio_sin_iva),
});

export const mapUpdatePlanFullDTOToEntity = (dto: UpdatePlanFullDTO): Plan => ({
  id_plan: dto.id_plan,
  segmento: normalizeNullableString(dto.segmento),
  producto: normalizeNullableString(dto.producto),
  bonete: normalizeNullableString(dto.bonete),
  nombre: normalizeNullableString(dto.nombre),
  nombre_plan: normalizeNullableString(dto.nombre_plan),
  capacidad: normalizeNullableNumber(dto.capacidad),
  capacidad_plan: normalizeNullableString(dto.capacidad_plan),
  capacidad_anterior: normalizeNullableNumber(dto.capacidad_anterior),
  precio_full_price: normalizeNullableNumber(dto.precio_full_price),
  precio_oferta: normalizeNullableNumber(dto.precio_oferta),
  tag_1: normalizeNullableString(dto.tag_1),
  tag_2: normalizeNullableString(dto.tag_2),
  beneficio_1: normalizeNullableString(dto.beneficio_1),
  beneficio_2: normalizeNullableString(dto.beneficio_2),
  beneficio_3: normalizeNullableString(dto.beneficio_3),
  beneficio_4: normalizeNullableString(dto.beneficio_4),
  cta_1: normalizeNullableString(dto.cta_1),
  link_1: normalizeNullableString(dto.link_1),
  cta_2: normalizeNullableString(dto.cta_2),
  link_2: normalizeNullableString(dto.link_2),
  aumento: normalizeNullableNumber(dto.aumento),
  precio_tv_digital: normalizeNullableNumber(dto.precio_tv_digital),
  precio_tv_max: normalizeNullableNumber(dto.precio_tv_max),
  promo_activa: normalizeNullableBoolean(dto.promo_activa),
  muestra_desde: normalizeNullableString(dto.muestra_desde),
  canales_tv_digital: normalizeNullableString(dto.canales_tv_digital),
  canales_tv_max: normalizeNullableString(dto.canales_tv_max),
  precio_no_cliente: normalizeNullableNumber(dto.precio_no_cliente),
  descripcion_oferta: normalizeNullableString(dto.descripcion_oferta),
  comercial_name: normalizeNullableString(dto.comercial_name),
  comercial_id: normalizeNullableString(dto.comercial_id),
  telefono_0800: normalizeNullableString(dto.telefono_0800),
  icono_tag_1: normalizeNullableString(dto.icono_tag_1),
  pre_beneficio_2_titulo: normalizeNullableString(dto.pre_beneficio_2_titulo),
  pre_beneficio_2_descripcion: normalizeNullableString(dto.pre_beneficio_2_descripcion),
  pre_beneficio_1_titulo: normalizeNullableString(dto.pre_beneficio_1_titulo),
  pre_beneficio_1_descripcion: normalizeNullableString(dto.pre_beneficio_1_descripcion),
  nombre_plan_tv: normalizeNullableString(dto.nombre_plan_tv),
  grilla_canales: normalizeNullableString(dto.grilla_canales),
  icono_bonete: normalizeNullableString(dto.icono_bonete),
  precio_sin_iva: normalizeNullableNumber(dto.precio_sin_iva),
});
