import { IPlanRepository } from "@proodos/application/Interfaces/IPlanRepository";
import { ILogger } from "@proodos/application/Interfaces/ILogger";
import { GetPlansDataService } from "@proodos/application/Services/Plan/GetPlansDataService";
import { Plan } from "@proodos/domain/Entities/Plan";

describe("GetPlansDataService", () => {
  it("should return a snapshot ordered by id_plan and trim string fields", async () => {
    const plans: Plan[] = [
      {
        id_plan: 10,
        segmento: "  POSPAGO  ",
        producto: "   ",
        bonete: null,
        nombre: "  Plan 10 GB  ",
        nombre_plan: " 10 GB ",
        capacidad: 10,
        capacidad_plan: " 10 GB ",
        capacidad_anterior: 8,
        precio_full_price: 10000,
        precio_oferta: 8500,
        tag_1: " Promo ",
        tag_2: "   ",
        beneficio_1: " Beneficio 1 ",
        beneficio_2: null,
        beneficio_3: undefined,
        beneficio_4: "   ",
        cta_1: " Comprar ",
        link_1: " https://example.com/plan-10 ",
        cta_2: "   ",
        link_2: null,
        aumento: 0,
        precio_tv_digital: null,
        precio_tv_max: null,
        promo_activa: true,
        muestra_desde: " 2026-03-31 ",
        canales_tv_digital: " 80 canales ",
        canales_tv_max: "   ",
        precio_no_cliente: 12000,
        descripcion_oferta: " Oferta online ",
        comercial_name: " Comercial 10 ",
        comercial_id: " ID10 ",
        telefono_0800: " 0800-123-456 ",
        icono_tag_1: " <svg>promo</svg> ",
        pre_beneficio_2_titulo: " Titulo 2 ",
        pre_beneficio_2_descripcion: " Descripcion 2 ",
        pre_beneficio_1_titulo: " Titulo 1 ",
        pre_beneficio_1_descripcion: " Descripcion 1 ",
        nombre_plan_tv: " Plan TV ",
        grilla_canales: " Grilla ",
        icono_bonete: " <svg>bonete</svg> ",
        precio_sin_iva: 7000,
      },
      {
        id_plan: 2,
        segmento: "   ",
        producto: " Alta linea ",
        bonete: " Destacado ",
        nombre: "  Plan 2 GB ",
        nombre_plan: " 2 GB ",
        capacidad: 2,
        capacidad_plan: null,
        capacidad_anterior: 1,
        precio_full_price: 5000,
        precio_oferta: 4200,
        tag_1: null,
        tag_2: null,
        beneficio_1: null,
        beneficio_2: null,
        beneficio_3: null,
        beneficio_4: null,
        cta_1: null,
        link_1: null,
        cta_2: null,
        link_2: null,
        aumento: null,
        precio_tv_digital: null,
        precio_tv_max: null,
        promo_activa: null,
        muestra_desde: null,
        canales_tv_digital: null,
        canales_tv_max: null,
        precio_no_cliente: null,
        descripcion_oferta: null,
        comercial_name: null,
        comercial_id: null,
        telefono_0800: null,
        icono_tag_1: null,
        pre_beneficio_2_titulo: null,
        pre_beneficio_2_descripcion: null,
        pre_beneficio_1_titulo: null,
        pre_beneficio_1_descripcion: null,
        nombre_plan_tv: null,
        grilla_canales: null,
        icono_bonete: null,
        precio_sin_iva: 3500,
      },
    ];

    const planRepository: jest.Mocked<IPlanRepository> = {
      create: jest.fn(),
      update: jest.fn(),
      updateFull: jest.fn(),
      patch: jest.fn(),
      patchFull: jest.fn(),
      getById: jest.fn(),
      getAll: jest.fn().mockResolvedValue(plans),
      exists: jest.fn(),
      delete: jest.fn(),
    };

    const logger: jest.Mocked<ILogger> = {
      info: jest.fn(),
      warn: jest.fn(),
      error: jest.fn(),
      debug: jest.fn(),
    };

    const service = new GetPlansDataService(planRepository, logger);

    const result = await service.execute();

    expect(logger.info).toHaveBeenCalledWith("[Service] GetPlansDataService.execute()");
    expect(planRepository.getAll).toHaveBeenCalledTimes(1);
    expect(Object.keys(result)).toEqual(["2", "10"]);
    expect(result["2"]).toMatchObject({
      id_plan: 2,
      segmento: null,
      producto: "Alta linea",
      bonete: "Destacado",
      nombre: "Plan 2 GB",
      nombre_plan: "2 GB",
      precio_sin_iva: 3500,
    });
    expect(result["10"]).toMatchObject({
      id_plan: 10,
      segmento: "POSPAGO",
      producto: null,
      nombre: "Plan 10 GB",
      nombre_plan: "10 GB",
      capacidad_plan: "10 GB",
      tag_1: "Promo",
      tag_2: null,
      beneficio_1: "Beneficio 1",
      beneficio_4: null,
      cta_1: "Comprar",
      link_1: "https://example.com/plan-10",
      cta_2: null,
      muestra_desde: "2026-03-31",
      canales_tv_digital: "80 canales",
      canales_tv_max: null,
      descripcion_oferta: "Oferta online",
      comercial_name: "Comercial 10",
      comercial_id: "ID10",
      telefono_0800: "0800-123-456",
      icono_tag_1: "<svg>promo</svg>",
      pre_beneficio_2_titulo: "Titulo 2",
      pre_beneficio_2_descripcion: "Descripcion 2",
      pre_beneficio_1_titulo: "Titulo 1",
      pre_beneficio_1_descripcion: "Descripcion 1",
      nombre_plan_tv: "Plan TV",
      grilla_canales: "Grilla",
      icono_bonete: "<svg>bonete</svg>",
      precio_sin_iva: 7000,
    });
  });
});
